# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "https://timgates2.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Tim Gates Jr. # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Full-Stack Developer</h1>
     <p>I'm a Junior developer specializing in Javascript, Rails and Angular.js.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "findme@timgatesjr.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "timgates2"
  google_plus: "107020662824072811734"
  instagram:
  linkedin:  https://www.linkedin.com/in/timgatesjr
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: "76561198087524999/"
  tumblr:
  twitter:
  wordpress:
  youtube: https://www.youtube.com/channel/UC-zPsFYcvrcpj8Bsu8OSULA

  # Scripts
  google_analytics: "UA-96995309-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
